// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MagicalGirl struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MagicalGirl) Reset()         { *m = MagicalGirl{} }
func (m *MagicalGirl) String() string { return proto.CompactTextString(m) }
func (*MagicalGirl) ProtoMessage()    {}
func (*MagicalGirl) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *MagicalGirl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicalGirl.Unmarshal(m, b)
}
func (m *MagicalGirl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicalGirl.Marshal(b, m, deterministic)
}
func (m *MagicalGirl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicalGirl.Merge(m, src)
}
func (m *MagicalGirl) XXX_Size() int {
	return xxx_messageInfo_MagicalGirl.Size(m)
}
func (m *MagicalGirl) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicalGirl.DiscardUnknown(m)
}

var xxx_messageInfo_MagicalGirl proto.InternalMessageInfo

func (m *MagicalGirl) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MagicalGirl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetMagicalGirlParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMagicalGirlParam) Reset()         { *m = GetMagicalGirlParam{} }
func (m *GetMagicalGirlParam) String() string { return proto.CompactTextString(m) }
func (*GetMagicalGirlParam) ProtoMessage()    {}
func (*GetMagicalGirlParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *GetMagicalGirlParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMagicalGirlParam.Unmarshal(m, b)
}
func (m *GetMagicalGirlParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMagicalGirlParam.Marshal(b, m, deterministic)
}
func (m *GetMagicalGirlParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMagicalGirlParam.Merge(m, src)
}
func (m *GetMagicalGirlParam) XXX_Size() int {
	return xxx_messageInfo_GetMagicalGirlParam.Size(m)
}
func (m *GetMagicalGirlParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMagicalGirlParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetMagicalGirlParam proto.InternalMessageInfo

type GetMagicalGirlResponce struct {
	MagicalGirls         []*MagicalGirl `protobuf:"bytes,1,rep,name=magicalGirls,proto3" json:"magicalGirls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetMagicalGirlResponce) Reset()         { *m = GetMagicalGirlResponce{} }
func (m *GetMagicalGirlResponce) String() string { return proto.CompactTextString(m) }
func (*GetMagicalGirlResponce) ProtoMessage()    {}
func (*GetMagicalGirlResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *GetMagicalGirlResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMagicalGirlResponce.Unmarshal(m, b)
}
func (m *GetMagicalGirlResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMagicalGirlResponce.Marshal(b, m, deterministic)
}
func (m *GetMagicalGirlResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMagicalGirlResponce.Merge(m, src)
}
func (m *GetMagicalGirlResponce) XXX_Size() int {
	return xxx_messageInfo_GetMagicalGirlResponce.Size(m)
}
func (m *GetMagicalGirlResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMagicalGirlResponce.DiscardUnknown(m)
}

var xxx_messageInfo_GetMagicalGirlResponce proto.InternalMessageInfo

func (m *GetMagicalGirlResponce) GetMagicalGirls() []*MagicalGirl {
	if m != nil {
		return m.MagicalGirls
	}
	return nil
}

func init() {
	proto.RegisterType((*MagicalGirl)(nil), "app.MagicalGirl")
	proto.RegisterType((*GetMagicalGirlParam)(nil), "app.GetMagicalGirlParam")
	proto.RegisterType((*GetMagicalGirlResponce)(nil), "app.GetMagicalGirlResponce")
}

func init() {
	proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47)
}

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0x28, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0x28, 0x50, 0x32, 0xe4, 0xe2, 0xf6, 0x4d,
	0x4c, 0xcf, 0x4c, 0x4e, 0xcc, 0x71, 0xcf, 0x2c, 0xca, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x44, 0xb9, 0x84, 0xdd, 0x53,
	0x4b, 0x90, 0x74, 0x05, 0x24, 0x16, 0x25, 0xe6, 0x2a, 0xf9, 0x71, 0x89, 0xa1, 0x0a, 0x07, 0xa5,
	0x16, 0x17, 0xe4, 0xe7, 0x25, 0xa7, 0x0a, 0x99, 0x70, 0xf1, 0xe4, 0x22, 0x84, 0x8b, 0x25, 0x18,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf4, 0x40, 0x4e, 0x41, 0x56, 0x8f, 0xa2, 0xca, 0x28, 0x9e,
	0x4b, 0x34, 0x1d, 0xc5, 0xbc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x37, 0x2e, 0x5e,
	0x88, 0x45, 0x30, 0x47, 0x4b, 0x80, 0x4d, 0xc2, 0xe2, 0x26, 0x29, 0x69, 0x2c, 0x32, 0x30, 0x67,
	0x25, 0xb1, 0x81, 0x83, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xb5, 0x61, 0x4f, 0x13,
	0x01, 0x00, 0x00,
}
